import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saksham Sharma — Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransition
      >
      <body
        className={`${geistSans.variable} ${geistMono.variable} -slate-800 antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
      </ThemeProvider>
    </html>
  );
}
